### ISSUE TITLE
decode功能改进

### ISSUE THREAD

**Issue by ghost** [bigmeow/JWT#1]
你好:
     我看了你的例子https://github.com/bigmeow/JWT。能跑起来。

```
 但是我另外生成了一个token的话
 "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL2xhcmF2ZWwtYXBpLWJvaWxlcnBsYXRlLWp3dC5kZXZcL2FwaVwvYXV0aFwvbG9naW4iLCJpYXQiOjE0NjU2NDcwMjMsImV4cCI6MTQ2NTY1MDYyMywibmJmIjoxNDY1NjQ3MDIzLCJqdGkiOiI1NDBiNTViMjY2ZDdhZDE4NzRlYjNhMzgzYWE5YWJiMyJ9.oiL873vWi0m_6UukC6UO0PFJVcH1i3FR8A-rLWpKnck"

 放入到输入框中就解析不了。但是放在https://jwt.io/里面都能解析成功。请问一下你的例子如何修改才能达到https://jwt.io/的效果?
```

**Comment by bigmeow** [comment]
@jnuc093 你是说你生成的token放到我那个例子的文本域里面就解析不了么？如果你是这个意思的话，首先你要确定我的例子里的秘钥和你正在用的生成的秘钥是不是同一个；第二，我观察到你的head部分的数据是：`{
  "typ": "JWT",
  "alg": "HS256"
}`

而我的Head部分是：`{
  "alg": "HS256"
}`,（我的head部分的数据是写在Jwt.Java 类里面的第60行代码，如下：
`JWSHeader header = new JWSHeader(JWSAlgorithm.HS256);`
可以看到我的head部分只设置了alg: HS256
）
所以你拿你的token到我那里去校验自然就无法通过了.
解决方法：
1. 秘钥一致
   2.Ctrl+F  将代码`JWSHeader header = new JWSHeader(JWSAlgorithm.HS256);`改成
   `JWSHeader header =new JWSHeader(JWSAlgorithm.HS256, JOSEObjectType.JWT, null, null, null, null, null, null, null, null, null, null, null);`，这样head部分数据就是
   `{
   "alg": "HS256",
   "typ": "JWT"
   }`了
   3.你的head数据顺序应该改为和我的一样

另外，我的例子生成的token ，放到https://jwt.io/ 也是可以解析成功的，所以你不必执着于你生成的token一定要我的也能校验。

**Comment by ghost** [comment]
多谢指导。我刚刚开始学习JWT看到你的例子不错。在你的例子上研究一番后发现了解决方法直接用这个类进行parse就能看到信息了:
joseObject = JOSEObject.parse(token);

**Comment by bigmeow** [comment]
@jnuc093 是的，我优化了一下，感谢指正，提交了
