### ISSUE TITLE
token失效问题

### ISSUE THREAD

**Issue by lhzwb2008** [bigmeow/JWT#10]
hi，请教一个问题，如果用户修改密码后，由于不存储状态，原来的access_token还会持续生效，请问这边的实现有防止旧token登陆的方案不？

**Comment by HuRuWo** [comment]
修改密码-->移除token-->必须重新登录-->得到新的token

**Comment by restmad** [comment]
JWT貌似只能等过期吧

**Comment by bigmeow** [comment]
其实可以把密码的MD5字符串也加密到token里，校验时密码也参与计算，改了密码肯定就校验不过了；
有的服务器端不想每次总是校验耗费计算力，生成后就会把token存放到服务器内存缓存里，比如redis、memcached中,request把token扔过来时看缓存里有没有？有的话是否过期？修改密码时把token移除，这是内存换计算力的做法
