### ISSUE TITLE
Algorithm HMACSHA256 not available

### ISSUE THREAD

**Issue by FullStackD** [bigmeow/JWT#3]
为什么会发生这样的结果

**Comment by bigmeow** [comment]
检查是否是jdk7 和javeSe1.7的环境 @FullStackD

**Comment by FullStackD** [comment]
是JDK7   我更改为1.8以后还是这样的错误  是需要修改Tomcat的JDK版本吗？  请问这是什么原因导致的呢？

**Comment by FullStackD** [comment]
问题已解决，我在 http://connect2id.com/products/nimbus-jose-jwt/jca-algorithm-support#alg-check 找到了答案
