### ISSUE TITLE
jwt 相关问题请教下

### ISSUE THREAD

**Issue by fantiq** [bigmeow/JWT#4]
1. jwt是提倡token每次请求都改变的
   改变的话 ： 客户端多线程并发请求 会导致第一个到达的请求可以 后边的请求就token失败
   不变的话 ：1. 程序无法控制token的过期时间 只能等token过期后 用户在重新登录（这个过程中即使用户频繁请求接口也无法避免）。2. token不变化就会导致重放攻击 不变的token 跟sessionID 基本没什么区别
2. jwt提倡将信息放在token第2段，第3段通过签名实现客户端无法恶意改token信息，但是token第2段是可以直接 base64_decode 拿到明文信息， 这样token泄漏就等于用户信息泄漏。目前我的处理是仅仅将用户的唯一识别（uid）加密后在生成token的
3. 用户信息放在token里面 当用户信息改变的话 就要 重新生成token ，修改用户信息是通过客户端请求触发的 接口可以生成新的token发给客户端，但 如果 这个修改是从后台操作的 这个新生成的token如何给到客户端。jwt中的一些实现是每次token解出来后去查寻数据库来更新用户信息，但是每次接口都去查用户信息的开销太大 还不如sessionID + redis 的结合
4. 用户退出登录的时候 token并未过期 如果服务端不处理将token加入黑名单 即使退出登录他的token还是可以使用的，这样的不方便还不如sessionID

**Comment by bigmeow** [comment]
你把JWT的token想得太复杂了，你可以这样理解，它就是模仿session的机制，session是存服务端，这个是存客户端，一次性交换用户信息，以减少服务端压力，用来做登录状态的身份校验还可以，做接口的权限的校验就显得拙荆见肘了，对于安全要求大的，需要另外一套机制来实现，author2.0这类的，像微信API接口类似，用分配的KEY和secret 来拿到accessToken,然后用accessToken来换token,然后用token来调用接口，还有加盐等等...
我的理解就是，**JWT它适用于前后端完全分离后，用来替代session的一个东西，真的不适合复杂的接口校验，需要配合其他手段**。
基于以上的理解，来说下你的问题。
第一点，如果你token不加盐的话，每次请求都更新改变token的话，其实老的token还是可以使用的，因为都是按规则生成的，你服务端没有存储token，只是做token合法性校验，所以不会存在第一个到达的请求可以校验成功、后面的请求失败问题；另外你token的变化不用那么频繁，可以这样： 假设token失效时间是半小时，那么每次校验token的时候，判断下距离时效时间还有多久，如果距离失效时间小于5分钟了，则生成新的TOKEN，返回客户端更新，这时候老的TOKEN在时间还没过期之前还是可以使用的，这样迸发的请求也是能拿到数据的，下次的请求则是用新的token请求。
**程序控制token过期时间**.这要区别一下，如果你是想**让某个用户的token马上过期，重新登录获取**的话，可以这样做：首先把该用户的ID放到某张TABLE或者redis里，作为一个黑名单的存在，然后在后端的token校验过滤器里加一段逻辑，在校验TOKEN后，取出TOKEN中存放的用户ID,然后拿这个ID去黑名单中找，如果存在，就不给客户端数据，直接返回状态让客户端重新登录，同时干掉这个黑名单中的用户id，因为我们只用一次嘛~
如果你想**让所有的用户TOKEN都强制过期**的话，可以在TOKEN中加入版本号信息，每次校验token后还要校验版本号，需要让大家都过期的话就升级下版本号，程序里校验token后再校验下版本号，发现升级就让所有低版本号的TOKEN失效，重新获取。
**token不变化就会导致重放攻击**.的确，但是你变了也没有办法抵御啊 ，别人可以拿到你新生成的TOKEN再继续请求啊，所以要靠其他方式实现，比如每次请求的时候带上客户端的标识（如果是APP的话可以用手机的UUID），然后拿到用户的ip,在后端做判断，如果这个标识的用户在这个ip一分钟请求的次数到了上限，就判定为恶意请求，可以禁用ip. 其实这个和token没多大关系，要自己来做防御的。

第二点，你说得没错，token不适合放重要敏感信息，适合放用户唯一标识，服务端拿到唯一标识后去数据库或者缓存拿用户数据；
第三，基于第二点，就不存在用户信息改变了要换token的可能，再怎么变用户唯一标识是不会变的，你可以将用户信息放redis啊 ，修改了用户信息就更新redis，TOKEN +redis的组合；
第四，用户在客户端退出，其实就是把本地存储的token给删除了而已，服务端是不用管的，这个不影响什么啊，对于普通用户来说，的确是实现了登录一样的效果啊。对于心怀恶意的人来说，由于退出时删除了本地的token，所以他是没有办法知道别人token的，所以不会对服务端造成任何损失，根本就没有假如黑名单的必要。
 回答得有点长，希望能给你帮助。

**Comment by fantiq** [comment]
@bigmeow 

> 你把JWT的token想得太复杂了，你可以这样理解，它就是模仿session的机制，session是存服务端，这个是存客户端，一次性交换用户信息，以减少服务端压力，用来做登录状态的身份校验还可以，做接口的权限的校验就显得拙荆见肘了，对于安全要求大的，需要另外一套机制来实现，author2.0这类的，像微信API接口类似，用分配的KEY和secret 来拿到accessToken,然后用accessToken来换token,然后用token来调用接口，还有加盐等等...

```
1. token是用户的识别标识这个是常识 不必解释
2. jwt 与 session 相比较 并找不到优势 ，至于减少服务端压力 其实并没有，session 会把用户信息存放在redis 目前我使用jwt 也是同样的方式(我使用的这个并不能说是jwt 我是将用户一些唯一识别信息以及过期时间做对称加密生成的token 并不会使用其他用户信息加入到token)。jwt的处理有的是每次token解出来都去查数据库的形式 IO 压力更大
3. 权限的校验这个是在服务端逻辑做的是无疑的 跟 token 没联系
4. auth2.0 解决的是三方授权登录问题，与jwt相比多了一个 refresh_token 但是token 与 refresh_token 都存在一个过期的问题。auth2.0 的refresh_token 是在服务方存放 也是服务方维护token(过期前更换) 包括 app_key 与 secret 这些信息

```

> 我的理解就是，JWT它适用于前后端完全分离后，用来替代session的一个东西，真的不适合复杂的接口校验，需要配合其他手段。
> 基于以上的理解，来说下你的问题。
> 第一点，如果你token不加盐的话，每次请求都更新改变token的话，其实老的token还是可以使用的，因为都是按规则生成的，你服务端没有存储token，只是做token合法性校验，所以不会存在第一个到达的请求可以校验成功、后面的请求失败问题；另外你token的变化不用那么频繁，可以这样： 假设token失效时间是半小时，那么每次校验token的时候，判断下距离时效时间还有多久，如果距离失效时间小于5分钟了，则生成新的TOKEN，返回客户端更新，这时候老的TOKEN在时间还没过期之前还是可以使用的，这样迸发的请求也是能拿到数据的，下次的请求则是用新的token请求。

```
1. token 如果在一定的长时间是不过期的 这样跟 sessionID 有什么区别，token不更新就存在安全问题(重放)
2. token更新就是为了安全的考虑(这个过程是 客户端每次请求的时候token 接口处理完会将数据和新的token再发给客户端 客户端更新token)，并发的时候就会出现我说的那个问题。
```

> 程序控制token过期时间.这要区别一下，如果你是想让某个用户的token马上过期，重新登录获取的话，可以这样做：首先把该用户的ID放到某张TABLE或者redis里，作为一个黑名单的存在，然后在后端的token校验过滤器里加一段逻辑，在校验TOKEN后，取出TOKEN中存放的用户ID,然后拿这个ID去黑名单中找，如果存在，就不给客户端数据，直接返回状态让客户端重新登录，同时干掉这个黑名单中的用户id，因为我们只用一次嘛~
> 如果你想让所有的用户TOKEN都强制过期的话，可以在TOKEN中加入版本号信息，每次校验token后还要校验版本号，需要让大家都过期的话就升级下版本号，程序里校验token后再校验下版本号，发现升级就让所有低版本号的TOKEN失效，重新获取。

```
这个地方 我并没有这个疑问 想要让一个用户掉线我可以直接删除redis信息 用户就必须重新登录 之前的token都没有用了
```

> token不变化就会导致重放攻击.的确，但是你变了也没有办法抵御啊 ，别人可以拿到你新生成的TOKEN再继续请求啊，所以要靠其他方式实现，比如每次请求的时候带上客户端的标识（如果是APP的话可以用手机的UUID），然后拿到用户的ip,在后端做判断，如果这个标识的用户在这个ip一分钟请求的次数到了上限，就判定为恶意请求，可以禁用ip. 其实这个和token没多大关系，要自己来做防御的。

```
1. 这个问题也的确是的 没有什么好方法 我一直在寻找。一直对jwt抱有希望也就是 希望jwt会有一个安全方面的功能，现在看来并没有 我目前的看法是 jwt与session相比并没有什么优势 目前使用https 来做(但是觉的这个也不安全 因为我们会抓取别人的数据 同时也要防止别人抓取我们的数据 --! )
2. ip 这个的限制 我目前是有这个功能 用来防止刷短信 刷接口 (但并没有卵用的 这个ip同样可以伪造 我们抓其他app的数据的时候 他们把我们公司的ip都封了 但是我们还是通过伪造ip绕过了 这点除非禁用掉用户端的代理 才能全面防御)
3. uuid同样不能绑定 用户会换设备 uuid只能做单设备登录
```

> 第二点，你说得没错，token不适合放重要敏感信息，适合放用户唯一标识，服务端拿到唯一标识后去数据库或者缓存拿用户数据；
> 第三，基于第二点，就不存在用户信息改变了要换token的可能，再怎么变用户唯一标识是不会变的，你可以将用户信息放redis啊 ，修改了用户信息就更新redis，TOKEN +redis的组合；
> 
> ```
> 我目前的做法是可以实现 token 频繁更换但是redis的用户信息是不变的 (我并不是将redis中的用户信息与token绑定的)
> ```
> 
> 第四，用户在客户端退出，其实就是把本地存储的token给删除了而已，服务端是不用管的，这个不影响什么啊，对于普通用户来说，的确是实现了登录一样的效果啊。对于心怀恶意的人来说，由于退出时删除了本地的token，所以他是没有办法知道别人token的，所以不会对服务端造成任何损失，根本就没有假如黑名单的必要。
> 
> ```
> 黑名单的做法 在一些jwt组件里都是有采用的。退出token还能使用这个问题我目前的做法是
> 退出登录就把redis用户信息清空 用户必须登录
> ```

**Comment by bigmeow** [comment]
@fantiq   你做的这个系统设计对安全的要求的确很高啊 ，如之前所说，我目前把JWT也只是定位成前后端完全分离后用来替代sessionID的一个东西，服务端的restful接口调用的授权完全是另一套，至于重放攻击、第三方抓取根本就不能指望它了，凡是按标准来做的东西都是有迹可循，有案可查。对了，目前我还没见过爬虫抓不到的数据，代价大小不同罢了。加个好友，有机会一起探讨下，你问的几个问题对我也有不小启发，我的qq就是我的网易邮箱账号

**Comment by hojit** [comment]
还没理解透，你还不如自己写了，session也会有并发请求失效的情况吧？
既然存在redis的，又要类似于session，还要避免重放攻击的话，自己设计一套吧。
