### ISSUE TITLE
关于数据安全传输的问题

### ISSUE THREAD

**Issue by a601942905git** [bigmeow/JWT#5]
根据您的描述,可以解决权限控制问题,每次客户端请求带上token,服务器端进行校验,校验通过才执行相应的操作,那么怎么保证每次传输数据的安全性？看过你介绍的2篇关于token的文章,理解的是每次请求对header和body中的数据进行编码,然后拼接,最后进行加密,生成签名,发送给服务器端,服务器端每次根据客户端相同的规则进行签名的生成,是不是每次客户端每次请求都要带上token和对数据加密生成的签名,服务器端需要校验token和签名(防止请求的数据被修改)。

**Comment by luokein** [comment]
应该如楼上所说，要不jwt完全没有防篡改的作用了

**Comment by bigmeow** [comment]
是的。
